### PR TITLE
made more robust by only checking for complete cases of x,y. 

### PR DESCRIPTION
**Pull request by smsaladi**
Other aesthetics could be NA without causing position_* issues

>"Sorry, I just realized that this solution could be buggy... I think it would be better to only check for complete cases of x and y not all the aesthetics that could, in principle, be missing but not cause position_* any issues.

>I'm thinking about color = NA, for example, that scale_color would deal with. 

Pull request with this suggestion."

### CODE REVIEW

**Comment by smsaladi** [comment]
Toy example:

```{R}
iris[iris$Sepal.Width < 3,]$Sepal.Width <- NA
ggplot(iris) + 
    geom_point(aes(x=Species, y=Sepal.Length, color=Sepal.Width), position=position_quasirandom()) +
    scale_color_brewer(na.value = "red")
```

Previous solution will result in iris[iris$Sepal.Width < 3,] entries not being plotted, when they should just be colored red.

**Comment by eclarke** [comment]
Should we warn the users of the cases that are being excluded due to NAs? I think ggplot does this in similar cases.

**Comment by smsaladi** [comment]
Thats probably a good idea.

**Comment by eclarke** [comment]
Awesome, thanks!

**Pull request merged**
